# Generated by Django 3.2.10 on 2022-10-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(default='phones/default_image.png', upload_to='phones')),
                ('model_no', models.CharField(max_length=255, unique=True)),
                ('processor', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('phone_os', models.CharField(max_length=100)),
                ('ram', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Phones',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
