# Generated by Django 3.2.10 on 2022-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone_os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='processor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='phones',
            name='ram',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
