# Generated by Django 3.2.10 on 2022-10-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20221019_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='picture',
            field=models.ImageField(default='phones/default_phone.png', upload_to='phones'),
        ),
    ]
